SELECT json_object_agg(name,object)
FROM(
    SELECT
        HOSTS.NAME as name,
        JSON_BUILD_OBJECT(
            'nodename',HOSTS.NAME,
            'hostname',HOSTS.NAME,
            'username', 'rundeck',
            'description',HOSTS.COMMENT,
            'tags',STRING_AGG(CONCAT('class=',PUPPETCLASSES.NAME), ','),
            'osFamily',OPERATINGSYSTEMS.TYPE,
            'osArch',ARCHITECTURES.NAME,
            'osName',OPERATINGSYSTEMS.NAME,
            'osVersion',OPERATINGSYSTEMS.MAJOR,
            'hostgroup',HOSTGROUPS.TITLE,
            'environment',ENVIRONMENTS.NAME
        ) as object
    FROM HOSTS 
    LEFT JOIN OPERATINGSYSTEMS ON OPERATINGSYSTEMS.ID = HOSTS.OPERATINGSYSTEM_ID
    LEFT JOIN ARCHITECTURES ON HOSTS.ARCHITECTURE_ID = ARCHITECTURES.ID
    LEFT JOIN HOSTGROUPS ON HOSTS.HOSTGROUP_ID = HOSTGROUPS.ID
    LEFT JOIN ENVIRONMENTS ON HOSTS.ENVIRONMENT_ID = ENVIRONMENTS.ID
    LEFT JOIN HOST_CLASSES ON HOSTS.ID = HOST_CLASSES.HOST_ID
    LEFT JOIN HOSTGROUP_CLASSES ON HOSTS.HOSTGROUP_ID = HOSTGROUP_CLASSES.HOSTGROUP_ID
    LEFT JOIN PUPPETCLASSES ON HOST_CLASSES.PUPPETCLASS_ID = PUPPETCLASSES.ID OR HOSTGROUP_CLASSES.PUPPETCLASS_ID = PUPPETCLASSES.ID
    GROUP BY
        HOSTS.ID, HOSTS.NAME, HOSTS.COMMENT,
        OPERATINGSYSTEMS.NAME, OPERATINGSYSTEMS.MAJOR, OPERATINGSYSTEMS.TYPE,
        ARCHITECTURES.NAME,
        HOSTGROUPS.ID, HOSTGROUPS.NAME, HOSTGROUPS.TITLE,
        ENVIRONMENTS.NAME
    ORDER BY HOSTS.ID ASC
) t;